version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  e2e-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install @umijs/test @hapi/joi
            - run: npm run ci
            - run: bash <(curl -s https://codecov.io/bash)

workflows:
    e2e-test:
      jobs:
        - e2e-test
